stages:
  - register

register_flow:
  stage: register
  image: python:3.8 # Replace with Python docker image
  script:
    - pip install -r requirements.txt # Install prefect package and other dependencies
    - prefect config set PREFECT_API_URL=$PREFECT_SERVER_URL # Make sure to configure PREFECT_SERVER_URL as an environment variable through GitLab CI settings
    - python flows/flow.py # Register flow with Prefect server
  only:
    - main # Register flow will only be executed when running on main branch
